
- hosts: all
  tasks:
  - name: build docker image
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/docker

  - name: creat  tag to image
    command: docker tag simple-devops-image mydocker111/simple-devops-image

  - name: push image to docker hub
    command: docker push mydocker111/simple-devops-image

  - name: push remove created images
    command: docker rmi -f simple-devops-image:latest  mydocker111/simple-devops-image
    ignore_errors: yes
